MODEL:
    META_ARCHITECTURE: "ProbabilisticGeneralizedRCNN"
    WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"

    BACKBONE:
        NAME: "build_resnet_fpn_backbone"
  # FREEZE_AT: 5

    RESNETS:
        OUT_FEATURES: ["res2", "res3", "res4", "res5"]

    FPN:
        IN_FEATURES: ["res2", "res3", "res4", "res5"]

    ANCHOR_GENERATOR:
        # One size for each in feature map
        SIZES: [[32], [64], [128], [256], [512]]
        # Three aspect ratios (same for all in feature maps)
        ASPECT_RATIOS: [[0.5, 1.0, 2.0]]

    RPN:
        IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
        PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
        PRE_NMS_TOPK_TEST: 1000  # Per FPN level
        # Detectron1 uses 2000 proposals per-batch,
        # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
        # which is approximately 1000 proposals per-image since the default
        # batch size for FPN is 2.
        POST_NMS_TOPK_TRAIN: 1000
        POST_NMS_TOPK_TEST: 1000
        
    ROI_MASK_HEAD:
        NAME: "MaskRCNNConvUpsampleHead"
        NUM_CONV: 4
        POOLER_RESOLUTION: 14

INPUT:
    MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)